[paths]
data_dir = "Data"
raw_data = "diamonds.csv"
processed_dir = "Data/processed"
train_data = "train.parquet"
test_data = "test.parquet"
model = "tabnet_model"
feature_metadata = "feature_metadata.pkl"
scaler = "scaler.pkl"
training_history = "training_history.pkl"
training_plot = "training_plot.png"
feature_importance = "feature_importance.csv"

[features]
categorical = ["cut", "color", "clarity"]
numerical = ["carat", "depth", "table", "x", "y", "z"]
target = "price_bwp"
exchange_rate = 13.5

[hparams]
n_d = 50
n_a = 56
n_steps = 9
gamma = 1.329
cat_emb_dim = 15  
mask_type = "entmax"

[hparams.optimizer_params]
lr=0.0466



[training]
seed = 42
test_size = 0.2
batch_size = 2048
max_epochs = 100
patience = 10
