[paths]
train_csv = "Data/diamonds.csv"
processed_dir = "Data/processed"
models = "models"

[features]
categorical = [ "cut", "color", "clarity",]
numerical = [ "carat", "depth", "table", "x", "y", "z",]
target = "price"

[model]
checkpoint = "models/tabnet_model"

[model.init]
n_d = 32
n_a = 43
n_steps = 5
gamma = 1.254584765120671
lambda_sparse = 0.0002279216849417837
mask_type = "entmax"
cat_emb_dim = 3

[model.fit]
max_epochs = 100
patience = 10
num_workers = 4
batch_size = 2048
virtual_batch_size = 256
drop_last = false

[model.init.optimizer_params]
lr = 0.019811397709919246
